jekyll:
    image: jekyll/jekyll:pages
    command: jekyll serve --watch --incremental
    ports:
        - 4000:4000
    volumes:
        - ./src:/srv/jekyll
        - ./vendor/bundle:/usr/local/bundle 
